# Generated by Django 5.1.2 on 2024-10-28 16:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('rub', 'Рубль'), ('dollar', 'Доллар'), ('euro', 'Евро'), ('yuan', 'Юань')], default='rub', max_length=6, verbose_name='Валюта')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'стоимость',
                'verbose_name_plural': 'Стоимости',
                'ordering': ('price',),
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'тип товара',
                'verbose_name_plural': 'Типы товаров',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('amount', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('barcode', models.CharField(db_index=True, max_length=13, validators=[django.core.validators.RegexValidator(message='Штрихкод должен иметь длину8 или 13 символов и состоять из цифр', regex='^\\d{8}|\\d{13}$')], verbose_name='Штрихкод')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('price', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.productprice', verbose_name='Цена')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.producttype')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('date_updated',),
            },
        ),
    ]
