# Generated by Django 5.1.2 on 2024-10-28 17:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_price_productprice_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-date_updated',), 'verbose_name': 'товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(db_index=True, max_length=13, validators=[django.core.validators.RegexValidator(message='Штрихкод должен иметь длину 8 или 13 символов и состоять из цифр', regex='^\\d{8}$|^\\d{13}$')], verbose_name='Штрихкод'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.producttype', verbose_name='Тип товара'),
        ),
    ]
