# Generated by Django 5.1.2 on 2024-10-30 08:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_options_alter_product_barcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(db_index=True, max_length=13, validators=[django.core.validators.RegexValidator(message='Штрихкод должен иметь длину 13 или 8 символов и состоять из цифр', regex='^\\d{13}$|^\\d{8}$')], verbose_name='Штрихкод'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='products.product', verbose_name='Товар'),
        ),
    ]
